/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MoveDetail,
} from './gesture';


export namespace Components {
  interface BottomDrawer {
    'expanded': boolean;
    'onMenuToggled': (boolean, finalY: number) => void;
    'onPositionChange': (detail: MoveDetail) => void;
    'startOffset': number;
  }
  interface BottomDrawerDemo {}
  interface FancyApp {}
}

declare global {


  interface HTMLBottomDrawerElement extends Components.BottomDrawer, HTMLStencilElement {}
  var HTMLBottomDrawerElement: {
    prototype: HTMLBottomDrawerElement;
    new (): HTMLBottomDrawerElement;
  };

  interface HTMLBottomDrawerDemoElement extends Components.BottomDrawerDemo, HTMLStencilElement {}
  var HTMLBottomDrawerDemoElement: {
    prototype: HTMLBottomDrawerDemoElement;
    new (): HTMLBottomDrawerDemoElement;
  };

  interface HTMLFancyAppElement extends Components.FancyApp, HTMLStencilElement {}
  var HTMLFancyAppElement: {
    prototype: HTMLFancyAppElement;
    new (): HTMLFancyAppElement;
  };
  interface HTMLElementTagNameMap {
    'bottom-drawer': HTMLBottomDrawerElement;
    'bottom-drawer-demo': HTMLBottomDrawerDemoElement;
    'fancy-app': HTMLFancyAppElement;
  }
}

declare namespace LocalJSX {
  interface BottomDrawer extends JSXBase.HTMLAttributes<HTMLBottomDrawerElement> {
    'expanded'?: boolean;
    'onMenuToggle'?: (event: CustomEvent<any>) => void;
    'onMenuToggled'?: (boolean, finalY: number) => void;
    'onPositionChange'?: (detail: MoveDetail) => void;
    'startOffset'?: number;
  }
  interface BottomDrawerDemo extends JSXBase.HTMLAttributes<HTMLBottomDrawerDemoElement> {}
  interface FancyApp extends JSXBase.HTMLAttributes<HTMLFancyAppElement> {}

  interface IntrinsicElements {
    'bottom-drawer': BottomDrawer;
    'bottom-drawer-demo': BottomDrawerDemo;
    'fancy-app': FancyApp;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


